version: "3.8"

services:
  app:
    build: ./app
    container_name: my_node_app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["node", "server.js"]

