version: '3.8'

services:
  nginx:
    image: mynginx
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
